console.log('Skills-First Starter Template');
console.log('==============================\n');
console.log('Get started:');
console.log('  npm run skill:discover  - Generate skills for your domain');
console.log('  npm run db:init         - Initialize database');
console.log('  npm run cli             - Test skills interactively');
console.log('  npm run migrate:promote - Promote fields to columns\n');
console.log('Documentation:');
console.log('  docs/progressive-formalization.md');
console.log('  docs/writing-skills.md');
console.log('  docs/migrations.md\n');
console.log('Example:');
console.log('  examples/ticket-system/\n');
